Dev-shoji
d-Tshoji/day-service pull request #2
Opened 2017-07-24 02:18 UTC by d-Tshoji

first request

2017-08-11 06:45 UTC, dninomiya commented on .gitignore
> +.sass-cache
distディレクトリも加えてほしい
pugやscssのプロジェクトは通常ビルド後のファイルはgitに含めない。(pugやcssから生み出されたhtml, cssなど)
これをまぜると複数人でpugやscssをいじる際、それぞれのコンパイル結果が1行になるので行単位でdiffを出すgithubの場合100%コンフリクトするため。

2017-08-11 06:45 UTC, dninomiya commented on src/pug/_footer.pug
> +          a(href=).footer__nav-item: p 施設について
- `.footer__nav` は div ではなく `nav` にしたい
- aタグの右のp不要（あってもよいがなくてもよいのでなくてよい）

2017-08-11 06:45 UTC, dninomiya commented on src/pug/_header.pug
> +    .header__nav
- a の子の p 不要
- .header__navi -> `nav.header__nav` としたい (navi は タグに合わせて nav にしたい）

2017-08-11 06:45 UTC, dninomiya commented on src/pug/index.pug
>    .main
main タグ使いたい main.main

2017-08-11 06:45 UTC, dninomiya commented on src/pug/index.pug
> +        while i--
- var の子供みたいなインデントだが、 -var と white は同じインデント位置でよい

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_about.scss
> +  .about {
indent がおかしいので beauty かけたし

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_about.scss
> +    //border: 1px solid greenyellow;
これは作業中だからだと思うけど、あえて・・・。コメント（不要な記述）は最終的には消しましょう〜

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_about.scss
> +      margin: 0 auto;
0 に px つけないのナイス 👍

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_about.scss
> +@media (min-width: 480px){
media の子供なのでインデントほしい (beautyかければok）

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_footer.scss
> +@media (max-width: 480px){
){ がくっついているので整形したい。 beauty で解決

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_footer.scss
> +      &:visited {
link と visited は丁寧すぎるので、通常のスタイルでOK
```
&-item {
  color: #BBBBBB;
  text-decoration: none;
  &:hover {
   ...
  }
}
```

あと色コードは基本小文字かつ6つつながりは3つに省略可能 BBBBBB -> bbb

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_header.scss
> +  box-shadow: 0px 10px 6px rgba(0, 0, 0, 0.3);
0px -> 0

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_header.scss
> +  overflow: visible;
default が visible なので不要

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_header.scss
> +  box-shadow: 0px 10px 6px rgba(0, 0, 0, 0.3);
0px -> 0

2017-08-11 06:45 UTC, dninomiya commented on src/scss/_main.scss
> +    transform: translate(-50%, -50%);
この場合 `transform: translate(-50%);` でいけた気が・・・（気のせいだったらすいません）

2017-08-11 06:45 UTC, dninomiya commented on src/scss/style.scss
> +@import url(../css/font-awesome.min.css);
CDNでやりたい。そしてプロジェクト内のfont-awesome系は消したい
詳しくは fontawesome cdn 使う　でぐぐるとよいです。

CDNってのはgoogle とかその他の会社が、人気のプラグインやfontを世界中の人が使いまわせるようにサーバーにあげてくれてて、その仕組を指す（厳密には違いますがそういう理解でoKです）

2017-08-23 09:14 UTC, deerboy commented
@d-Tshoji 
`main.main` の件、 .main は .hero にあたる想定のものだったのですね。
mainタグは通常主なコンテンツ全体を囲むもの（headerとfooterの間）であるため、
`.main` が `.hero` を想定したものであるならばお手数ですが `.hero` に戻してください。
文脈読み取れず申し訳ない・・。

2017-08-23 09:16 UTC, deerboy commented on src/scss/_header.scss
>      box-shadow: 0 9px 6px -3px rgba(0,0,0,0.3);
`rgba(0,0,0,0.3);` , の間にスペースが欲しい。 beauty かけたら一発でなおると思うのでおなしゃす！

2017-08-23 09:22 UTC, dninomiya requested changes
レビューもう一個追加しました

2017-08-23 09:22 UTC, deerboy commented on src/scss/style.scss
> -@import url(../css/font-awesome.min.css);
ここを純粋に消すのではなく、CDN参照 (fontawesome cdn でぐぐる）らないとfont awesome が効かなくなるかと思うんですが、別の部分でCDN参照してたりします？

2017-08-23 09:25 UTC, deerboy commented on src/scss/_header.scss
>      box-shadow: 0 9px 6px -3px rgba(0,0,0,0.3);
こちらこの後のcommit で解消されてますね。done!

2017-08-23 09:29 UTC, deerboy commented on src/scss/style.scss
> -@import url(../css/font-awesome.min.css);
正解を書くと、

```
@import url(CDNのURL);
```

2017-08-24 01:26 UTC, d-Tshoji commented on src/scss/style.scss
> -@import url(../css/font-awesome.min.css);
_base.pugのhead内に以下を記述
```link(rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css")```

_header.pugの4行目に以下を記述で表示されてはいる状態です。
```<i class="fa fa-bars header-sp-menu" aria-hidden="true"></i>```

2017-08-24 02:08 UTC, merged